services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 13102001
      POSTGRES_DB: spending_management
    ports:
      - '5432:5432'
