export const MoneySpendingCategories = [
  'FOOD',
  'TRANSPORTATION',
  'HOUSING',
  'UTILITIES',
  'ENTERTAINMENT',
  'HEALTHCARE',
  'EDUCATION',
  'SAVINGS',
  'DEBT',
  'CLOTHING',
  'MISCELLANEOUS',
];

export const categories = {
  FOOD: [
    'ăn uống',
    'bữa ăn',
    'cơm',
    'phở',
    'bún',
    'hủ tiếu',
    'mì',
    'cháo',
    'đồ ăn',
    'thức ăn',
    'thực phẩm',
    'nhà hàng',
    'quán ăn',
    'cafe',
    'trà sữa',
    'nước ngọt',
    'bia',
    'rượu',
  ],
  TRANSPORTATION: [
    'vé xe bus',
    'vé xe buýt',
    'vé xe khách',
    'tàu hỏa',
    'tàu điện',
    'tàu điện ngầm',
    'máy bay',
    'xăng',
    'vé xe',
    'vé tàu',
    'vé máy bay',
    'gửi xe',
    'tiền grab',
    'tiền be',
    'xanh sm',
  ],
  HOUSING: [
    'tiền thuê nhà',
    'thuê phòng',
    'nhà trọ',
    'căn hộ',
    'chung cư',
    'mua nhà',
    'nhà ở',
    'bất động sản',
  ],
  UTILITIES: [
    'điện',
    'nước',
    'gas',
    'internet',
    'wifi',
    'truyền hình cáp',
    'điện thoại',
    'phí dịch vụ',
    'rác thải',
    'phí vệ sinh',
  ],
  ENTERTAINMENT: [
    'xem phim',
    'rạp chiếu phim',
    'karaoke',
    'trò chơi',
    'game',
    'du lịch',
    'dã ngoại',
    'ca nhạc',
    'hòa nhạc',
    'thể thao',
    'bóng đá',
    'bơi lội',
    'mua sắm',
    'đi chơi',
  ],
  HEALTHCARE: [
    'bệnh viện',
    'phòng khám',
    'thuốc',
    'khám bệnh',
    'xét nghiệm',
    'bảo hiểm y tế',
    'chích ngừa',
    'tiêm vaccine',
    'khẩu trang',
  ],
  EDUCATION: [
    'học phí',
    'sách vở',
    'bút',
    'vở',
    'trường học',
    'đại học',
    'cao đẳng',
    'lớp học',
    'khóa học',
    'gia sư',
    'học thêm',
  ],
  SAVINGS: [
    'tiết kiệm',
    'gửi ngân hàng',
    'lãi suất',
    'gửi tiết kiệm',
    'quỹ dự phòng',
  ],
  DEBT: [
    'nợ',
    'vay tiền',
    'trả góp',
    'thẻ tín dụng',
    'lãi suất vay',
    'vay ngân hàng',
  ],
  CLOTHING: [
    'quần áo',
    'áo',
    'quần',
    'váy',
    'giày',
    'dép',
    'mũ',
    'nón',
    'áo khoác',
    'đồng phục',
    'phụ kiện',
    'túi xách',
  ],
  MISCELLANEOUS: [
    'chi phí khác',
    'lặt vặt',
    'phí phát sinh',
    'mua linh tinh',
    'chi tiêu linh tinh',
  ],
};
